services:
  1tomatomap:
    build:
      context: .
      dockerfile: Dockerfile
    image: 1tomatomap:latest
    container_name: 1tomatomap
    ports:
      - "${APP_PORT:-7200}:80"
    restart: unless-stopped
