services:
  1tomatoartmap:
    build:
      context: .
      dockerfile: Dockerfile
    image: 1tomatoartmap:latest
    container_name: 1tomatoartmap
    ports:
      - "${APP_PORT:-7200}:80"
    restart: unless-stopped
